// Generated by gencpp from file rto_msgs/GrapplerReadings.msg
// DO NOT EDIT!


#ifndef RTO_MSGS_MESSAGE_GRAPPLERREADINGS_H
#define RTO_MSGS_MESSAGE_GRAPPLERREADINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rto_msgs
{
template <class ContainerAllocator>
struct GrapplerReadings_
{
  typedef GrapplerReadings_<ContainerAllocator> Type;

  GrapplerReadings_()
    : stamp()
    , seq(0)
    , numServos(0)
    , torqueEnabled(false)
    , angles()
    , velocities()
    , errors()
    , channels()
    , ids()
    , cwAxesLimits()
    , ccwAxesLimits()  {
    }
  GrapplerReadings_(const ContainerAllocator& _alloc)
    : stamp()
    , seq(0)
    , numServos(0)
    , torqueEnabled(false)
    , angles(_alloc)
    , velocities(_alloc)
    , errors(_alloc)
    , channels(_alloc)
    , ids(_alloc)
    , cwAxesLimits(_alloc)
    , ccwAxesLimits(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef uint32_t _numServos_type;
  _numServos_type numServos;

   typedef uint8_t _torqueEnabled_type;
  _torqueEnabled_type torqueEnabled;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angles_type;
  _angles_type angles;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocities_type;
  _velocities_type velocities;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _errors_type;
  _errors_type errors;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _channels_type;
  _channels_type channels;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _ids_type;
  _ids_type ids;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _cwAxesLimits_type;
  _cwAxesLimits_type cwAxesLimits;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _ccwAxesLimits_type;
  _ccwAxesLimits_type ccwAxesLimits;





  typedef boost::shared_ptr< ::rto_msgs::GrapplerReadings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rto_msgs::GrapplerReadings_<ContainerAllocator> const> ConstPtr;

}; // struct GrapplerReadings_

typedef ::rto_msgs::GrapplerReadings_<std::allocator<void> > GrapplerReadings;

typedef boost::shared_ptr< ::rto_msgs::GrapplerReadings > GrapplerReadingsPtr;
typedef boost::shared_ptr< ::rto_msgs::GrapplerReadings const> GrapplerReadingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rto_msgs::GrapplerReadings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rto_msgs::GrapplerReadings_<ContainerAllocator1> & lhs, const ::rto_msgs::GrapplerReadings_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.seq == rhs.seq &&
    lhs.numServos == rhs.numServos &&
    lhs.torqueEnabled == rhs.torqueEnabled &&
    lhs.angles == rhs.angles &&
    lhs.velocities == rhs.velocities &&
    lhs.errors == rhs.errors &&
    lhs.channels == rhs.channels &&
    lhs.ids == rhs.ids &&
    lhs.cwAxesLimits == rhs.cwAxesLimits &&
    lhs.ccwAxesLimits == rhs.ccwAxesLimits;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rto_msgs::GrapplerReadings_<ContainerAllocator1> & lhs, const ::rto_msgs::GrapplerReadings_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rto_msgs::GrapplerReadings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rto_msgs::GrapplerReadings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rto_msgs::GrapplerReadings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53d1f6c81df9b5242320201fe0231738";
  }

  static const char* value(const ::rto_msgs::GrapplerReadings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53d1f6c81df9b524ULL;
  static const uint64_t static_value2 = 0x2320201fe0231738ULL;
};

template<class ContainerAllocator>
struct DataType< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rto_msgs/GrapplerReadings";
  }

  static const char* value(const ::rto_msgs::GrapplerReadings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint32 seq\n"
"uint32 numServos\n"
"bool torqueEnabled\n"
"float32[] angles		# in degrees\n"
"float32[] velocities	# in rpm\n"
"uint32[] errors\n"
"uint32[] channels\n"
"uint32[] ids\n"
"float32[] cwAxesLimits 	# in degrees\n"
"float32[] ccwAxesLimits	# in degrees\n"
;
  }

  static const char* value(const ::rto_msgs::GrapplerReadings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.seq);
      stream.next(m.numServos);
      stream.next(m.torqueEnabled);
      stream.next(m.angles);
      stream.next(m.velocities);
      stream.next(m.errors);
      stream.next(m.channels);
      stream.next(m.ids);
      stream.next(m.cwAxesLimits);
      stream.next(m.ccwAxesLimits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GrapplerReadings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rto_msgs::GrapplerReadings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rto_msgs::GrapplerReadings_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "numServos: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numServos);
    s << indent << "torqueEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.torqueEnabled);
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "errors[]" << std::endl;
    for (size_t i = 0; i < v.errors.size(); ++i)
    {
      s << indent << "  errors[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.errors[i]);
    }
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.channels[i]);
    }
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "cwAxesLimits[]" << std::endl;
    for (size_t i = 0; i < v.cwAxesLimits.size(); ++i)
    {
      s << indent << "  cwAxesLimits[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cwAxesLimits[i]);
    }
    s << indent << "ccwAxesLimits[]" << std::endl;
    for (size_t i = 0; i < v.ccwAxesLimits.size(); ++i)
    {
      s << indent << "  ccwAxesLimits[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ccwAxesLimits[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RTO_MSGS_MESSAGE_GRAPPLERREADINGS_H
