// Generated by gencpp from file rto_msgs/SetGripperState.msg
// DO NOT EDIT!


#ifndef RTO_MSGS_MESSAGE_SETGRIPPERSTATE_H
#define RTO_MSGS_MESSAGE_SETGRIPPERSTATE_H

#include <ros/service_traits.h>


#include <rto_msgs/SetGripperStateRequest.h>
#include <rto_msgs/SetGripperStateResponse.h>


namespace rto_msgs
{

struct SetGripperState
{

typedef SetGripperStateRequest Request;
typedef SetGripperStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGripperState
} // namespace rto_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rto_msgs::SetGripperState > {
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::rto_msgs::SetGripperState&) { return value(); }
};

template<>
struct DataType< ::rto_msgs::SetGripperState > {
  static const char* value()
  {
    return "rto_msgs/SetGripperState";
  }

  static const char* value(const ::rto_msgs::SetGripperState&) { return value(); }
};


// service_traits::MD5Sum< ::rto_msgs::SetGripperStateRequest> should match
// service_traits::MD5Sum< ::rto_msgs::SetGripperState >
template<>
struct MD5Sum< ::rto_msgs::SetGripperStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rto_msgs::SetGripperState >::value();
  }
  static const char* value(const ::rto_msgs::SetGripperStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rto_msgs::SetGripperStateRequest> should match
// service_traits::DataType< ::rto_msgs::SetGripperState >
template<>
struct DataType< ::rto_msgs::SetGripperStateRequest>
{
  static const char* value()
  {
    return DataType< ::rto_msgs::SetGripperState >::value();
  }
  static const char* value(const ::rto_msgs::SetGripperStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rto_msgs::SetGripperStateResponse> should match
// service_traits::MD5Sum< ::rto_msgs::SetGripperState >
template<>
struct MD5Sum< ::rto_msgs::SetGripperStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rto_msgs::SetGripperState >::value();
  }
  static const char* value(const ::rto_msgs::SetGripperStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rto_msgs::SetGripperStateResponse> should match
// service_traits::DataType< ::rto_msgs::SetGripperState >
template<>
struct DataType< ::rto_msgs::SetGripperStateResponse>
{
  static const char* value()
  {
    return DataType< ::rto_msgs::SetGripperState >::value();
  }
  static const char* value(const ::rto_msgs::SetGripperStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RTO_MSGS_MESSAGE_SETGRIPPERSTATE_H
