// Generated by gencpp from file rto_msgs/SetGripperStateResponse.msg
// DO NOT EDIT!


#ifndef RTO_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H
#define RTO_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rto_msgs
{
template <class ContainerAllocator>
struct SetGripperStateResponse_
{
  typedef SetGripperStateResponse_<ContainerAllocator> Type;

  SetGripperStateResponse_()
    {
    }
  SetGripperStateResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGripperStateResponse_

typedef ::rto_msgs::SetGripperStateResponse_<std::allocator<void> > SetGripperStateResponse;

typedef boost::shared_ptr< ::rto_msgs::SetGripperStateResponse > SetGripperStateResponsePtr;
typedef boost::shared_ptr< ::rto_msgs::SetGripperStateResponse const> SetGripperStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rto_msgs::SetGripperStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rto_msgs/SetGripperStateResponse";
  }

  static const char* value(const ::rto_msgs::SetGripperStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rto_msgs::SetGripperStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGripperStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rto_msgs::SetGripperStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rto_msgs::SetGripperStateResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RTO_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H
